# Generated by Django 4.0.1 on 2022-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='URL',
            field=models.URLField(blank=True),
        ),
    ]
